platform :ios, '8.0'
pod 'AFNetworking'
pod 'SVProgressHUD', '2.0-beta'
pod 'SDWebImage'
pod 'JSQMessagesViewController'
pod 'STTweetLabel'
pod 'KILabel', '1.0.0'
pod 'DZNPhotoPickerController/Editor'